// Função para gerar uma senha aleatória com o comprimento especificado
function gerarSenhaAleatoria(comprimento) {
    const caracteres = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+';
    let senha = '';
    for (let i = 0; i < comprimento; i++) {
        senha += caracteres.charAt(Math.floor(Math.random() * caracteres.length));
    }
    return senha;
}

// Função para gerar uma senha inquebrável com pelo menos 35 caracteres
function gerarSenhaInquebravel() {
    const caracteres = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+';
    let senha = '';
    const comprimentoMinimo = 35;
    while (senha.length < comprimentoMinimo) {
        senha += caracteres.charAt(Math.floor(Math.random() * caracteres.length));
    }
    return senha;
}

// Objeto contendo todas as informações organizadas
const informacoes = {
    hackers: [
        "HackerName123#0000",
        "DarkCoder87",
        "GhostByte",
        "PhantomHacker",
        "ViralVortex",
        "HackHarmony",
        "CodeCataclysm",
        "ByteBlast",
        "VirusVault",
        "CyberVault",
        "ShadowSaber",
        "DigitalSaber",
        "ZeroSaber",
        "CodeChaos",
        "ByteBlitz",
        "ShadowSilhouette",
        "DigitalSilhouette",
        "ZeroSilhouette",
        "HackHorizon",
        "PhantomHorizon",
        "VirusVelocity",
        "CyberVelocity",
        "ShadowStrike",
        "DigitalStrike",
        "ZeroStrike",
        "HackHeartbeat",
        "PhantomHeartbeat",
        "CodeConqueror",
        "ByteBlade",
        "ShadowSonic",
        "DigitalSonic",
        "ZeroSonic",
        "PhantomSonic",
        "HackSpectrum",
        "VirusVanguard",
        "CyberVanguard",
        "CodeCraze",
        "ByteBounty",
        "ShadowShade",
        "DigitalShade",
        "ZeroShade",
        "PhantomShade",
        "HackHive",
        "VirusVortex",
        "CyberVortex",
        "CodeCortex",
        "ByteByte",
        "ShadowByte",
        "DigitalByte",
        "ZeroByte",
        "PhantomByte",
        "HackFlow",
        "VirusVelocity",
        "CyberVelocity",
        "CodeCurrent",
        "ByteBoom",
        "ShadowSurge",
        "DigitalSurge",
        "ZeroSurge",
        "PhantomSurge",
        "HackSpark",
        "VirusVoltage",
        "CyberVoltage",
        "CodeCharge",
        "ByteBolt",
        "ShadowShock",
        "DigitalShock",
        "ZeroShock",
        "PhantomShock",
        "HackBlaze",
        "VirusVapor",
        "CyberVapor",
        "CodeFire",
        "ByteBurn",
        "ShadowFlame",
        "DigitalFlame",
        "ZeroFlame",
        "PhantomFlame",
        "HackBlitz",
        "VirusVortex",
        "CyberVortex",
        "CodeCyclone",
        "ByteBlast",
        "ShadowStorm",
        "DigitalStorm",
        "ZeroStorm",
        "PhantomStorm",
        "HackWave",
        "VirusVortex",
        "CyberVortex",
        "CodeCascade",
        "ByteBlast",
        "ShadowStream",
        "DigitalStream",
        "ZeroStream",
        "PhantomStream",
        "HackWhirl",
        "VirusVortex",
        "CyberVortex",
        "CodeCyclone",
        "ByteBlast"
    ],
    
    discord: [
        "LuarNoturno",
        "GuerreiroDigital",
        "EstrelaCadente",
        "MestreSombras",
        "PandaMisterioso",
        "GatoCurioso",
        "LobisomemFeroz",
        "UnicornioMajestoso",
        "DragaoAlado",
        "SereiaEncantada",
        "FenixVermelha",
        "NuvemCinzenta",
        "LendaUrbana",
        "MagoImortal",
        "BruxaMalvada",
        "FantasmaSombrio",
        "AnjoCaido",
        "EspiritoLivre",
        "VampiroNoturno",
        "NinjaSilencioso",
        "PirataAventureiro",
        "ExploradorPerdido",
        "FadaCelestial",
        "MarinheiroSolitario",
        "AventureiroCorajoso",
        "TesouroEscondido",
        "MisticoSagrado",
        "GuardiaoEterno",
        "FeiticeiraLua",
        "CaçadorEstelar",
        "GuerreiraAmazona",
        "ViajanteEstelar",
        "CavaleiroDragao",
        "SamuraiHonrado",
        "BrigaoCibernético",
        "AlquimistaMisterioso",
        "SábioAncião",
        "AssassinoSombrio",
        "CaçadoraFantasmas",
        "GuardaFlorestal",
        "MestreEspionagem",
        "CavaleiroVingador",
        "LutadorLendario",
        "MercenarioCorajoso",
        "PistoleiroDestemido",
        "HeroiAnonimo",
        "RangerSelvagem",
        "MagoElemental",
        "CavaleiraLunar",
        "RebeldeCibernetico",
        "PioneiroFuturista",
        "ExploradorGalatico",
        "SobreviventeApoçalitpico",
        "NavegadorEstelar",
        "AventureiroEspacial",
        "GuardiaoTerra",
        "AnjoGuarda",
        "AndarilhoEstelar",
        "LoboSolitario",
        "CruzadorGalactico",
        "ArqueiroEstrelar",
        "ConquistadorCosmico",
        "CaçadorEstrelas",
        "ArquitetoVirtual",
        "DuelistaGalactico",
        "DetetiveEstelar",
        "NavegadorCósmico",
        "MestreArcano",
        "SamuraiFuturista",
        "NômadeVagante",
        "NinjaFuturista",
        "LutadorEstelar",
        "ArqueiroGalactico",
        "CaçadoraSombras",
        "ExploradorCosmico",
        "AlmiranteEspacial",
        "CaçadoraEstrelas",
        "EngenheiroEstelar",
        "VagabundoCósmico",
        "MagoCibernético",
        "PirataCósmico",
        "AventureiroInterstelar",
        "GladiadorGalactico",
        "LendaEstelar",
        "CaçadoraGalactica",
        "CaçadorExtraterrestre",
        "MercenarioEstelar",
        "GuerreiroCosmico",
        "AstronautaCorajoso",
        "GuardiaoGalactico",
        "CaçadorFuturista",
        "CavaleiraEstelar",
        "ArqueiraCósmica",
        "CaçadorCibernético",
        "GuardaEstelar",
        "GladiadoraGalactica",
        "MestreFuturista",
        "GuardiaoEstelar",
        "ArquitetoEstelar",
        "ArqueiraEstelar",
        "MagoEstelar",
        "PirataEstelar",
        "MercenariaFuturista",
        "LendaCósmica",
        "ExploradoraEstelar",
        "ArqueiraGalactica",
        "CavaleiraCósmica",
        "NinjaEspacial",
        "AventureiraEstelar",
        "CavaleiraGalactica",
        "ExploradoraGalactica",
        "ArqueiraCósmica",
        "GuerreiraEstelar",
        "EngenheiraEstelar",
        "PirataCibernética",
        "AventureiraCósmica",
        "CavaleiraEstelar",
        "ArqueiraCósmica",
        "GuardiaGalactica",
        "ArqueiraFuturista",
        "CavaleiraFuturista",
        "PirataFuturista",
        "GuerreiraCósmica",
        "CaçadoraFuturista",
        "ArqueiraEstelar",
        "NinjaCósmico",
        "ArqueiraEstelar",
        "ExploradoraFuturista",
        "NinjaGalactico",
        "PirataGalactica",
        "CavaleiraCibernética",
        // Adicione mais usernames do Discord conforme necessário
    ],
    gangsters: [
        "Gângster Inc.",
        "CrimeCorp",
        "ShadowSyndicate",
        "DigitalMafia",
        "Black Widow Gang",
        "Dead End Boys",
        "Iron Horsemen",
        "Road Warriors",
        "Satan's Soldiers",
        "Black Mafia",
        "Latin Kings",
        "Bandidos Motorcycle Club",
        "Outlaws Motorcycle Club",
        "Sons of Silence",
        "The Order",
        "The Company",
        "The Brotherhood",
        "The Syndicate",
        "The Mob",
        "The Crips",
        "The Bloods",
        "The Aryan Brotherhood",
        "The Triads",
        "The Yakuza",
        "The Cartel",
        "The Outfit",
        "The Mafiya",
        "The Yardies",
        "The Hells Angels",
        "The Ndrangheta",
        "The Gambino Crime Family",
        "The Genovese Crime Family",
        "The Bonanno Crime Family",
        "The Colombo Crime Family",
        "The Lucchese Crime Family",
        "The DeCavalcante Crime Family",
        "The Barksdale Organization",
        "The Soprano Crime Family",
        "The DiMeo Crime Family",
        "The Corleone Family",
        "The Tattaglia Family",
        "The Barzini Family",
        "The Stracci Family",
        "The Cuneo Family",
        "The Greco Mafia Family",
        "The Granados Cartel",
        "The Salazar Cartel",
        "The Montoya Cartel",
        "The Sinaloa Cartel",
        "The Juarez Cartel",
        "The Tijuana Cartel",
        "The Zetas Cartel",
        "The Gulf Cartel",
        "The Norte del Valle Cartel",
        "The FARC",
        "The Shining Path",
        "The Camorra",
        "The 'Ndrangheta",
        "The Triad Society",
        "The Aryan Brotherhood",
        "The Mexican Mafia",
        "The Mara Salvatrucha (MS-13)",
        "The Crips",
        "The Bloods",
        "The Black Guerrilla Family",
        "The Folk Nation",
        "The People Nation",
        "The Aryan Brotherhood of Texas",
        "The Latin Kings",
        "The 18th Street Gang",
        "The Hells Angels",
        "The Mongols Motorcycle Club",
        "The Vagos Motorcycle Club",
        "The Bandidos Motorcycle Club",
        "The Outlaws Motorcycle Club",
        "The Pagan's Motorcycle Club",
        "The Sons of Silence Motorcycle Club",
        "The Warlocks Motorcycle Club",
        "The Diablos Motorcycle Club",
        "The Gypsy Joker Motorcycle Club",
        "The Highwaymen Motorcycle Club",
        "The Loners Motorcycle Club",
        "The Iron Order Motorcycle Club",
        "The Bandidos Motorcycle Club",
        "The Outlaws Motorcycle Club",
        "The Sons of Silence Motorcycle Club",
        "The Mongols Motorcycle Club",
        "The Vagos Motorcycle Club",
        "The Hells Angels Motorcycle Club",
        "The Pagans Motorcycle Club",
        "The Warlocks Motorcycle Club",
        "The Highwaymen Motorcycle Club",
        "The Rebels Motorcycle Club",
        "The Galloping Goose Motorcycle Club",
        "The Comanchero Motorcycle Club",
        "The Notorious Motorcycle Club",
        "The Satudarah Motorcycle Club",
        "The Bandidos Motorcycle Club",
        "The Mongols Motorcycle Club",
        "The Hells Angels Motorcycle Club",
        "The Outlaws Motorcycle Club",
        "The Pagan's Motorcycle Club",
        "The Sons of Silence Motorcycle Club",
        "The Vagos Motorcycle Club",
        "The Warlocks Motorcycle Club",
        "The Diablos Motorcycle Club",
        "The Gypsy Joker Motorcycle Club",
        "The Highwaymen Motorcycle Club",
        "The Bandidos Motorcycle Club",
        "The Outlaws Motorcycle Club",
        "The Sons of Silence Motorcycle Club",
        "The Mongols Motorcycle Club",
        "The Vagos Motorcycle Club",
        "The Hells Angels Motorcycle Club",
        "The Pagans Motorcycle Club",
        "The Warlocks Motorcycle Club",
        "The Highwaymen Motorcycle Club",
        "The Rebels Motorcycle Club",
        "The Galloping Goose Motorcycle Club",
        "The Comanchero Motorcycle Club",
        "The Notorious Motorcycle Club",
        "The Satudarah Motorcycle Club",
    ],
    
    forum: [
        "CyberNinja",
        "ByteMaster",
        "CodeWarrior",
        "DigitalGuru",
        "TechSavvy",
        "HackerPro",
        "CryptoWizard",
        "NetPioneer",
        "WebWanderer",
        "OnlineGuru",
        "ForumNinja",
        "DataDynamo",
        "InfoHunter",
        "GeekGoddess",
        "ByteBabe",
        "TechTitan",
        "CyberSleuth",
        "PixelPirate",
        "CodeCrusader",
        "DigitalNomad",
        "CyberWarlock",
        "ByteBandit",
        "WebWiz",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDiva",
        "GeekGuru",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWizard",
        "HackerMaster",
        "CryptoWizard",
        "NetNavigator",
        "DataDude",
        "GeekGoddess",
        "PixelPirate",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGuru",
        "PixelPioneer",
        "CodeCommando",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGuru",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSleuth",
        "CyberGuru",
        "ByteBender",
        "WebHero",
        "HackerHideout",
        "CryptoCoder",
        "NetNavigator",
        "DataDiva",
        "GeekGod",
        "PixelPirate",
        "CodeCrusader",
        "DigitalDynamo",
        "CyberLegend",
        "ByteBandit",
        "WebWizard",
        "HackerHero",
        "CryptoCrusader",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        "CodeCommander",
        "InfoSeeker",
        "CyberCommando",
        "ByteBoss",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDude",
        "GeekGuru",
        "PixelPioneer",
        "CodeCraftsman",
        "DigitalNomad",
        "CyberWizard",
        "ByteBrawler",
        "WebWarrior",
        "HackerHaven",
        "CryptoGenius",
        "NetNinja",
        "DataDetective",
        "GeekGoddess",
        "PixelPioneer",
        
    ],
    redesSociais: [
        "Ana Silva",
        "Pedro Santos",
        "Mariana Oliveira",
        "Lucas Pereira",
        "Joana Costa",
        "André Almeida",
        "Carla Martins",
        "Rui Fernandes",
        "Sofia Sousa",
        "Daniel Silva",
        "Inês Pereira",
        "Tiago Santos",
        "Rita Oliveira",
        "Diogo Costa",
        "Margarida Almeida",
        "Hugo Martins",
        "Catarina Fernandes",
        "Bruno Sousa",
        "Marta Silva",
        "Nuno Pereira",
        "Beatriz Santos",
        "Fábio Oliveira",
        "Vanessa Almeida",
        "Francisco Martins",
        "Patrícia Sousa",
        "Rodrigo Silva",
        "Ingrid Oliveira",
        "Vasco Santos",
        "Laura Almeida",
        "Gonçalo Martins",
        "Diana Sousa",
        "Leonardo Silva",
        "Isabel Oliveira",
        "Manuel Santos",
        "Carolina Almeida",
        "Miguel Martins",
        "Sara Sousa",
        "Paulo Silva",
        "Amanda Oliveira",
        "Gabriel Santos",
        "Tatiana Almeida",
        "Alexandre Martins",
        "Ana Sousa",
        "Luís Silva",
        "Bianca Oliveira",
        "Guilherme Santos",
        "Verónica Almeida",
        "Fernando Martins",
        "Renata Sousa",
        "César Silva",
        "Jéssica Oliveira",
        "Rafael Santos",
        "Teresa Almeida",
        "Simão Martins",
        "Vanessa Sousa",
        "Vitor Silva",
        "Andreia Oliveira",
        "Matias Santos",
        "Joana Almeida",
        "Leandro Martins",
        "Raquel Sousa",
        "Ricardo Silva",
        "Diana Oliveira",
        "Rui Santos",
        "Carla Almeida",
        "Pedro Martins",
        "Mafalda Sousa",
        "Gustavo Silva",
        "Mariana Oliveira",
        "David Santos",
        "Natália Almeida",
        "Bruno Martins",
        "Juliana Sousa",
        "Mário Silva",
        "Tânia Oliveira",
        "Simone Santos",
        "Fernanda Almeida",
        "Eduardo Martins",
        "Cristina Sousa",
        "Vasco Silva",
        "Alexandra Oliveira",
        "Rúben Santos",
        "Carolina Almeida",
        "Gustavo Oliveira",
        "Andreia Santos",
        "Eduarda Almeida",
        "Sérgio Martins",
        "Bárbara Sousa",
        "Ricardo Silva",
        "Sílvia Oliveira",
        "Rodrigo Santos",
        "Sara Almeida",
        "Carlos Martins",
        "Tatiana Sousa",
        "Marco Silva",
        "Susana Oliveira",
        "André Santos",
        "Carolina Almeida",
        "Cristiano Martins",
        "Ana Sousa",
        "Pedro Silva",
        "Inês Oliveira",
        "Diogo Santos",
        "Joana Almeida",
        "Manuela Martins",
        "Rafaela Sousa",
        "Bruno Silva",
        "Daniela Oliveira",
        "Nuno Santos",
        "Marta Almeida",
        "António Martins",
        "Mariana Sousa",
        "Luís Silva",
        "Sofia Oliveira",
        "Hugo Santos",
        "Carla Almeida",
        "Rui Martins",
        "Rita Sousa",
        "João Silva",
        "Ingrid Oliveira",
        "Tiago Santos",
        "Catarina Almeida",
        "Joana Martins",
        "Pedro Sousa",
        "Margarida Silva",
        "André Oliveira",
        "Lucas Santos",
        "Ana Almeida",
        "Gabriel Martins",
        "Sara Oliveira",
        "Bruno Santos",
        "Marta Almeida",
        "Francisco Oliveira",
        "Patrícia Santos",
        "Rodrigo Silva",
        "Inês Almeida",
        "Leonardo Martins",
        "Vanessa Oliveira",
        "Miguel Santos",
        "Rita Almeida",
        "Daniel Oliveira",
        "Sofia Martins",
        "Hugo Oliveira",
        "Carolina Santos",
        "Rafael Almeida",
        "Ana Oliveira",
        "Bruno Santos",
        "Inês Almeida",
        "Gustavo Oliveira",
    
        // Adicione mais nomes de redes sociais conforme necessário
    ],
    metin2: [
        "GângsterMetin",
        "MetinMaster",
        "ShadowBlade",
        "DarkWarrior",
        "LâminaEterna",
        "DragãoLendário",
        "EspíritoDivino",
        "CaçadorSombrio",
        "EstrelaCelestial",
        "GuardiãoMisterioso",
        "ElementalPortuguês",
        "MestreEterno",
        "SombraArdente",
        "AlmaRúnica",
        "GuerreiroEspiritual",
        "LâminaLuminosa",
        "MestreVermelho",
        "DragãoPerdido",
        "CaçadorGuerrilheiro",
        "EspíritoMítico",
        "EstrelaDourada",
        "GuardiãoDivino",
        "ElementalLendário",
        "MestreSombrio",
        "DragãoPortuguês",
        "SombraMisteriosa",
        "GuerreiroCelestial",
        "LâminaMística",
        "EspíritoSagrado",
        "EstrelaMisteriosa",
        "GuardiãoEterno",
        "ElementalArdente",
        "MestreRúnico",
        "DragãoLuminoso",
        "CaçadorDivino",
        "AlmaCelestial",
        "GuerreiroPortuguês",
        "LâminaDivina",
        "EspíritoSombrio",
        "EstrelaEterna",
        "GuardiãoLendário",
        "ElementalSagrado",
        "MestreMisterioso",
        "DragãoSombrio",
        "SombraDivina",
        "CaçadorLendário",
        "AlmaLuminosa",
        "GuerreiroMisterioso",
        "LâminaPortuguês",
        "EspíritoLendário",
        "EstrelaArdente",
        "GuardiãoCelestial",
        "ElementalMisterioso",
        "MestreDivino",
        "DragãoDivino",
        "SombraPortuguês",
        "CaçadorSagrado",
        "AlmaMística",
        "GuerreiroEterno",
        "LâminaMisteriosa",
        "EspíritoDivino",
        "EstrelaLendário",
        "GuardiãoPortuguês",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        "GuerreiroPortuguês",
        "LâminaSagrado",
        "EspíritoPortuguês",
        "EstrelaDivino",
        "GuardiãoSagrado",
        "ElementalLendário",
        "MestreCelestial",
        "DragãoMisterioso",
        "SombraDivina",
        "CaçadorEterno",
        "AlmaPortuguês",
        "GuerreiroSagrado",
        "LâminaLendário",
        "EspíritoDivino",
        "EstrelaPortuguês",
        "GuardiãoLendário",
        "ElementalDivino",
        "MestreSagrado",
        "DragãoCelestial",
        "SombraLendário",
        "CaçadorDivino",
        "AlmaDivina",
        // Adicione mais nomes de personagens do Metin2 conforme necessário
    ],
};

// Função para gerar informações aleatórias
function gerarInformacoes() {
    const informacoesGeradas = {};
    for (const key in informacoes) {
        if (Array.isArray(informacoes[key])) {
            const lista = informacoes[key];
            informacoesGeradas[key] = lista[Math.floor(Math.random() * lista.length)];
        } else {
            informacoesGeradas[key] = informacoes[key];
        }
    }
    // Gerar senhas para cada clique no botão
    informacoesGeradas.senha = gerarSenhaAleatoria(10);
    informacoesGeradas.senhaInquebravel = gerarSenhaInquebravel();
    return informacoesGeradas;
}

// Função para exibir informações na página
function exibirInformacoes() {
    const informacoesGeradas = gerarInformacoes();
    const resultadoDiv = document.getElementById("resultado");
    resultadoDiv.innerHTML = `
        <p><strong>Hacker:</strong> ${informacoesGeradas.hackers}</p>
        <p><strong>Discord:</strong> ${informacoesGeradas.discord}</p>
        <p><strong>Gangsters:</strong> ${informacoesGeradas.gangsters}</p>
        <p><strong>Fórum:</strong> ${informacoesGeradas.forum}</p>
        <p><strong>Redes Sociais:</strong> ${informacoesGeradas.redesSociais}</p>
        <p><strong>Metin2:</strong> ${informacoesGeradas.metin2}</p>
        <p><strong>Senha:</strong> ${informacoesGeradas.senha}</p>
        <p><strong>Senha Inquebrável:</strong> ${informacoesGeradas.senhaInquebravel}</p>
    `;
}

// Chama a função para exibir informações quando a página é carregada
window.addEventListener('DOMContentLoaded', exibirInformacoes);

// Evento de clique para gerar informações
document.getElementById("gerarIdentidade").addEventListener("click", exibirInformacoes);
